[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = ["ALL"]
ignore = [
    "G004",    # logging statement uses f-string
    "TD002",   # missing author in todo
    "TD003",   # missing issue link in todo
    "D105",    # missing docstring in magic methods
]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = [
    "INP001",  # implicit namespace
]
"tests/*test_*.py" = [
    "ANN201",  # missing return type annotation
    "S101",    # use of assert in tests
]

[tool.ruff.format]
quote-style = "double"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
]
